const INDUSTRY_POOL = ['90.BK0448', '90.BK1201', '90.BK0459', '90.BK1215', '90.BK0475', '90.BK0726', '90.BK1328', '90.BK1340', '90.BK1325']
const CACHE_SECONDS = { boards: 30, kline: 60 }
const ALLOWED_ORIGINS = new Set(['https://sc5839.github.io', 'http://127.0.0.1:5173', 'http://127.0.0.1:5174', 'http://127.0.0.1:5175', 'http://127.0.0.1:5176'])

function corsHeaders(request) { const origin = request.headers.get('Origin'); return { 'Access-Control-Allow-Origin': ALLOWED_ORIGINS.has(origin) ? origin : 'https://sc5839.github.io', 'Access-Control-Allow-Methods': 'GET, OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type', Vary: 'Origin' } }
function json(request, body, status = 200, extra = {}) { return new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json; charset=utf-8', ...corsHeaders(request), ...extra } }) }
async function upstream(url) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 8_000); try { const response = await fetch(url, { signal: controller.signal, headers: { Referer: 'https://data.eastmoney.com/zjlx/', 'User-Agent': 'Mozilla/5.0 (compatible; AidonFundDashboard/1.0)' } }); if (!response.ok) throw new Error(`上游返回 ${response.status}`); return await response.json() } finally { clearTimeout(timeout) } }
async function cached(request, ttl, produce) { const cache = caches.default; const key = new Request(request.url, { method: 'GET' }); const hit = await cache.match(key); if (hit) return hit; const payload = await produce(); const response = json(request, payload, 200, { 'Cache-Control': `public, max-age=${ttl}`, 'X-Data-Cache': 'MISS' }); await cache.put(key, response.clone()); return response }
function normalizeBoards(payload) { return (payload.data?.diff || []).map((item) => ({ code: item.f12, name: item.f14, price: item.f2, change: item.f3, flow: Number((item.f62 / 100000000).toFixed(2)), ratio: item.f184 })).filter((item) => item.code && item.name && Number.isFinite(item.flow)).sort((a, b) => b.flow - a.flow).map((item, index) => ({ ...item, rank: index + 1 })) }
async function boards(request) { return cached(request, CACHE_SECONDS.boards, async () => { const payload = await upstream(`https://push2.eastmoney.com/api/qt/ulist.np/get?fltt=2&invt=2&fields=f12,f14,f2,f3,f62,f184&secids=${INDUSTRY_POOL.join(',')}`); const rows = normalizeBoards(payload); if (!rows.length) throw new Error('东方财富未返回有效行业行情'); return { source: '东方财富公开行情', collectedAt: new Date().toISOString(), cacheSeconds: CACHE_SECONDS.boards, rows, crossCheck: { provider: '新浪财经', status: 'pending', note: '新浪公开接口的板块分类口径与东方财富不同，尚未验证稳定对应关系；当前不以其替代主源。' } } }) }
async function kline(request, code) { if (!/^BK\d{4}$/.test(code)) throw new Error('无效的板块代码'); return cached(request, CACHE_SECONDS.kline, async () => { const payload = await upstream(`https://push2his.eastmoney.com/api/qt/stock/kline/get?secid=90.${code}&klt=101&fqt=1&lmt=60&end=20500101&fields1=f1,f2,f3,f4,f5,f6&fields2=f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61`); const klines = payload.data?.klines || []; if (!klines.length) throw new Error('东方财富未返回有效日 K 数据'); return { source: '东方财富公开行情', collectedAt: new Date().toISOString(), cacheSeconds: CACHE_SECONDS.kline, name: payload.data?.name, klines } }) }
export default { async fetch(request) { if (request.method === 'OPTIONS') return new Response(null, { headers: corsHeaders(request) }); if (request.method !== 'GET') return json(request, { error: '仅支持 GET 请求' }, 405); const url = new URL(request.url); try { if (url.pathname === '/health') return json(request, { ok: true, service: 'aidon-market-data', now: new Date().toISOString() }); if (url.pathname === '/api/market/boards') return await boards(request); if (url.pathname === '/api/market/kline') return await kline(request, url.searchParams.get('code') || 'BK0448'); return json(request, { error: '接口不存在' }, 404) } catch (error) { return json(request, { error: '行情源暂时不可用', detail: error instanceof Error ? error.message : '未知错误', collectedAt: new Date().toISOString(), fallback: '请稍后重试；页面会保留上次成功数据或演示行。' }, 502) } } }
